### ISSUE TITLE
Can't download models from Baidu. Can you publish weights to google drive?

### ISSUE THREAD

**Issue by IamSVP94** [gaobb/DLDL-v2#6]

**Comment by gaobb** [comment]
Hi,

you can download the pre-trained weights from Google Drive. The download details are on the [DLDL-v2 Project Page](https://csgaobb.github.io/Projects/DLDL-v2.html).

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give  for free. Honestly, that’s pretty cheap compared to most of these services.
